fix: add lua modules to openresty
coreruleset/modsecurity-crs-docker pull request #208
Opened 2024-02-15 19:46 UTC by fzipi

2024-02-15 19:53 UTC, theseion commented
Oh, was this your question earlier, whether to use `lua-rocks` for OpenResty to install the modules? For the OpenResty image that may be the better option, TBH. I'd prefer all packages to come from the same source (in this case, all lua modules from the Lua package manager). But it probably doesn't make huge difference.

2024-02-15 21:23 UTC, fzipi commented
Yes, exactly. That was my question. No worries, I'll change this one.

2024-02-16 14:02 UTC, theseion requested changes

2024-02-16 14:02 UTC, theseion commented on openresty/Dockerfile-alpine
> +ARG LUA_ROCKS_MODULES
```suggestion
ARG LUA_MODULES
```

2024-02-17 06:30 UTC, theseion commented on docker-bake.hcl
> +    "lua-lzlib",
Wrong package name for Debian. We need to separate Alpine and Debian modules.

2024-02-19 07:15 UTC, theseion commented on openresty/Dockerfile-alpine
> +    for module in lua-resty-openidc ${LUA_MODULES}; do \
Now I think it makes sense to move `lua-resty-openidc` to the bake file as well.

2024-02-19 15:20 UTC, fzipi commented
Well, I would love to see the maintainer @TafkaMax chiming on this in the future. We mentioned that we wouldn't maintain the image, and I think this was more work than expected for openresty.
- git must be installed for luarocks to build `lua-zlib`. This pointed me to a problem in our alpine image, where the module `lua-lzlib` is different from `lua-zlib`, and it is unmaintained and the repo is archived.
- then everything is built in the last layer. I think the alpine-fat might not make sense if there is one additional step building all the lua modules and then copying the results to the final image. My 2 cents.

👉 In the end, if there is no maintenance for this image, I would drop it. We don't need the additional work. 🤷

2024-02-19 17:41 UTC, theseion approved these changes

2024-02-19 17:42 UTC, theseion commented
Agreed. Let's give them the benefit of the doubt for now ;)

2024-02-19 17:42 UTC, merged