feat(utf8): add variable for validating utf8
coreruleset/modsecurity-crs-docker pull request #21
Opened 2020-12-29 20:10 UTC by fzipi

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

This variable is being used by the CRS testing framework (taken from the regression test docs):

Requirements
============
There are Three requirements for running the OWASP CRS regressions.

1. You must have ModSecurity specify the location of your error.log, this is done in the config.py file
2. ModSecurity must be in DetectionOnly (or anomaly scoring) mode
3. You must disable IP blocking based on previous events

Note: The test suite compares timezones -- if your test machine and your host machine are in different timezones this can cause bad results

To accomplish 2. and 3. you may use the following rule in your setup.conf:

```
SecAction "id:900005,\
  phase:1,\
  nolog,\
  pass,\
  ctl:ruleEngine=DetectionOnly,\
  ctl:ruleRemoveById=910000,\
  setvar:tx.paranoia_level=4,\
  setvar:tx.crs_validate_utf8_encoding=1,\
  setvar:tx.arg_name_length=100,\
  setvar:tx.arg_length=400"
```

So we need that variable if we want to run proper tests as the doc says.

2020-12-29 20:27 UTC, fzipi commented
After reviewing, we use more parameters for the test that aren't reflected as env vars.

I think the main cause for not taking a look at these is because, well, those tests are disabled.

2021-06-02 20:28 UTC, franbuehler requested changes
There is an error in the sed statement and the rule is not set inside the container.

It should be:
```
# Activate UTF8 validation
if [ -n "$VALIDATE_UTF8_ENCODING" ]; then
  sed -z -E -i 's/#SecAction.{6}id:900950.*tx\.crs_validate_utf8_encoding=1\"/SecAction \\\n  \"id:900950, \\\n   phase:1, \\\n   nolog, \\\n   pass, \\\n   t:none, \\\n   setvar:tx.crs_validate_utf8_encoding=1\"/' /etc/modsecurity.d/owasp-crs/crs-setup.conf
fi
```

What I mean is `tx\.crs_validate_utf8_encoding=1` instead of `tx\.setvar:tx.crs_validate_utf8_encoding=1`

Then it works!

2021-06-06 13:07 UTC, fzipi commented
@franbuehler Definitely, good catch! Now it should be good to go.

2021-06-22 13:06 UTC, franbuehler approved these changes

2021-06-22 13:09 UTC, franbuehler commented
LGTM. I did not test it again. But it should work. I tested in the first review.

2021-06-23 00:11 UTC, merged