docker-compose 3.7 with x-defaults
coreruleset/modsecurity-crs-docker pull request #211
Opened 2024-02-23 23:07 UTC by daminuxfork

Add x-default config

2024-02-24 15:38 UTC, fzipi approved these changes
Thanks, good addition!

2024-02-25 07:08 UTC, theseion requested changes

2024-02-25 07:08 UTC, theseion commented on docker-compose.yaml
> +version: '3.7'
The `version` field is only informative. It's removal has been recommended for some time now: https://docs.docker.com/compose/compose-file/04-version-and-name/.

2024-02-25 07:08 UTC, theseion commented on docker-compose.yaml
> +    #ENFORCE_BODYPROC_URLENCODED: 1
Missing space after the comment marker.

2024-02-25 07:08 UTC, theseion commented on docker-compose.yaml
> +    #MAX_NUM_ARGS: 255
Missing space after the comment marker.

2024-02-25 07:08 UTC, theseion commented on docker-compose.yaml
> +      - "80:80"
That port mapping is intentional ;)
```suggestion
      - "80:8080"
```

2024-02-26 21:18 UTC, theseion approved these changes

2024-02-26 21:20 UTC, merged

2024-02-26 21:20 UTC, theseion commented
Thanks @daminuxfork!