feat(apache): switch to pcre2
coreruleset/modsecurity-crs-docker pull request #218
Opened 2024-03-17 13:18 UTC by fzipi

Use pcre for building on apache

2025-03-02 15:52 UTC, theseion commented
Note that the failing test in the httpd builds is ok. The test has an override to make it work on the CI, which will no longer be necessary once we update to the new images. I'll push a change to CRS to update the override so this PR can be properly verified.

2025-03-05 16:26 UTC, airween requested changes

2025-03-05 16:26 UTC, airween commented on apache/Dockerfile-alpine
> +    ./configure --with-yajl --with-ssdeep --with-lmdb --with-pcre2; \
```suggestion
    ./configure --with-yajl --with-ssdeep --with-pcre2; \
```
mod_security2 module does not have `--with-lmdb` option.

2025-03-07 05:57 UTC, theseion commented on apache/Dockerfile-alpine
> +    ./configure --with-yajl --with-ssdeep --with-lmdb --with-pcre2; \
That flag is currently only used in the Alpine builds. Is that a mistake? Shouldn't both nginx builds have the flag?

2025-03-11 05:53 UTC, theseion commented
@fzipi ready for review.

2025-03-11 07:44 UTC, airween approved these changes
LGTM

2025-03-11 13:36 UTC, fzipi commented
We need an extra approver...

2025-03-12 05:53 UTC, theseion commented
I've added @airween to the containers team.

2025-03-12 11:59 UTC, merged