feat: override full modsecurity.conf file
coreruleset/modsecurity-crs-docker pull request #239
Opened 2024-04-26 21:08 UTC by fzipi

- move all variables from modsecurity-override.conf to modsecurity.conf
- add extra variables to configure modsecurity.conf params
- update README with new variables

2024-04-26 21:11 UTC, fzipi commented on src/etc/modsecurity.d/modsecurity.conf
This is based on latest v3 recommended (as the comment said in our code). I guess it is good for using with v2 also.

Note: I've explicitly enabled 200006 instead of 200001. Maybe we want to add a flag for this, but I think it is the better option.

2024-04-27 07:48 UTC, theseion requested changes

2024-04-27 07:48 UTC, theseion commented on README.md
> +| MODSEC_COOKIE_FORMAT | The cookie format used (Default: `0`)  :warning: Do not touch unless you really know what you are doing. |
Link to docs?

2024-04-27 07:48 UTC, theseion commented on README.md
> +| MODSEC_UNICODE_MAPPING | The unicode Code Point to use form the default file(Default: `20127`). See [SecUnicodeMapFile](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v2.
```suggestion
| MODSEC_UNICODE_MAPPING | Unicode code point to use (Default: `20127`). See [SecUnicodeMapFile](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secunicodemapfile) |
```

2024-04-27 07:48 UTC, theseion commented on README.md
> +| MODSEC_UPLOAD_KEEP_FILES | Configures whether or not the intercepted files will be kept after transaction is processed.  (Default: `RelevantOnly`) Accepted values: `On`, `Off`, `RelevantOnly`. See
```suggestion
| MODSEC_UPLOAD_KEEP_FILES | Configures whether the intercepted files will be kept after transaction is processed.  (Default: `RelevantOnly`) Accepted values: `On`, `Off`, `RelevantOnly`. See [SecUploadKeepFiles](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secuploadkeepfiles)
```

2024-04-27 07:48 UTC, theseion commented on src/etc/modsecurity.d/modsecurity.conf
I agree.

2024-04-27 12:39 UTC, fzipi commented on README.md
> +| MODSEC_COOKIE_FORMAT | The cookie format used (Default: `0`)  :warning: Do not touch unless you really know what you are doing. |
Added.

2024-05-01 12:44 UTC, fzipi commented
No comments from @dune73 or @airween. Will merge by EOD.

2024-05-05 15:36 UTC, merged

2024-05-05 23:42 UTC, ruipin commented
This pull request broke my setup using `nginx-alpine`.

To fix it I had to force the following values inside my docker compose:

```
      MODSEC_AUDIT_STORAGE_DIR: /var/log/modsecurity/audit/
      MODSEC_DISABLE_BACKEND_COMPRESSION: 'Off'
      MODSEC_UPLOAD_KEEP_FILES: 'Off'
```

The first one seems due to a typo - `MODSEC_AUDIT_STORAGE_DIR` is used by the new file, but the environment variable that is used for the default value is `MODSEC_AUDIT_STORAGE`.

The second one doesn't seem to have a default value.

The third one would complain that `RelevantOnly` was not a valid value, and it needed `On` or `Off`.