fix: nginx module more headers
coreruleset/modsecurity-crs-docker pull request #310
Opened 2024-12-12 17:10 UTC by fzipi

## what

- compile header_more modules

## why

- fix cors

2024-12-25 09:15 UTC, theseion requested changes

2024-12-25 09:15 UTC, theseion commented on .github/workflows/verifyimage.yml
> +          if "${{ matrix.target }}" == "nginx" ; then
```suggestion
          if grep -q  "nginx <<< "${{ matrix.target }}"; then
```

2024-12-30 08:17 UTC, theseion requested changes

2024-12-30 08:17 UTC, theseion commented on .github/workflows/verifyimage.yml
> +          if grep -q  "nginx <<< ${{ matrix.target }}" ; then
```suggestion
          if grep -q  "nginx "<<< "${{ matrix.target }}"; then
```

2024-12-30 08:17 UTC, theseion commented on nginx/Dockerfile
> +        modules=+("--add-dynamic-module=../${repo}"); \
```suggestion
        modules+=("--add-dynamic-module=../${repo}"); \
```

2024-12-30 08:17 UTC, theseion commented on nginx/Dockerfile
> +    for module in ${NGINX_DYNAMIC_MODULES}; \
```suggestion
    declare -a modules; \
    for module in ${NGINX_DYNAMIC_MODULES}; \
```

2024-12-30 08:17 UTC, theseion commented on nginx/Dockerfile
> +    ./configure --with-compat ${modules[@]} ;\
```suggestion
    ./configure --with-compat ${modules[@]}; \
```

2024-12-30 08:17 UTC, theseion commented on nginx/Dockerfile-alpine
> +    for module in ${NGINX_DYNAMIC_MODULES}; \
```suggestion
    declare -a modules;
    for module in ${NGINX_DYNAMIC_MODULES}; \
```

2024-12-30 08:17 UTC, theseion commented on nginx/Dockerfile-alpine
> +        repo=$(awk -F'/' '{print $2}' <<< $module); \
```suggestion
        repo=$(awk -F'/' '{print $2}' <<< "${module}"); \
```

2024-12-30 11:31 UTC, theseion requested changes

2024-12-30 11:31 UTC, theseion commented on nginx/Dockerfile-alpine
> +    declare -a modules;
```suggestion
    declare -a modules; \
```

2024-12-30 13:12 UTC, theseion requested changes

2024-12-30 14:59 UTC, fzipi commented on nginx/Dockerfile-alpine
> +    for module in ${NGINX_DYNAMIC_MODULES}; \
I think the one to remove is the one after `do`?

2024-12-30 15:40 UTC, theseion commented on nginx/Dockerfile-alpine
> +    for module in ${NGINX_DYNAMIC_MODULES}; \
No :)

2024-12-30 15:42 UTC, theseion commented on nginx/Dockerfile-alpine
> +    for module in ${NGINX_DYNAMIC_MODULES}; \
Yes, you're right.

2025-01-02 11:02 UTC, fzipi commented on nginx/Dockerfile
> +    do; \
```suggestion
    do \
```

2025-01-02 11:02 UTC, fzipi commented on nginx/Dockerfile-alpine
> +    do; \
```suggestion
    do \
```

2025-01-05 08:44 UTC, theseion approved these changes
Finally :D

2025-01-05 08:45 UTC, merged