Add `MODSEC_DISABLE_BACKEND_COMPRESSION` env variable
coreruleset/modsecurity-crs-docker pull request #78
Opened 2022-05-19 11:37 UTC by karelorigin

Currently the `SecDisableBackendCompression` option is completely unavailable, even though CRS requires it to be `On` by default. This PR fixes that. I've left out NGINX since it only supports V3 where the option still has to be implemented.

**Note: changes here will have no effect until https://github.com/coreruleset/modsecurity-docker/pull/116 gets merged.**

2022-10-20 17:27 UTC, theseion requested changes

2022-10-20 17:27 UTC, theseion commented on README.md
> +| BACKEND  | The backend address (and optional port) of the backend server. (Default: the container's default router, port 81) (Examples: 192.0.2.2, 192.0.2.2:80, http://172.17.0.1:8000) ||
Does that make more sense?

```suggestion
| BACKEND  | The backend address (and optional port) of the backend server. (Default: the container's default router port 81) (Examples: 192.0.2.2, 192.0.2.2:80, http://172.17.0.1:8000) |
```

2022-10-20 17:27 UTC, theseion commented on README.md
> +| MODSEC_DISABLE_BACKEND_COMPRESSION | ModSecurity string that can enable or disable backend compression (Default: `On`) **(⚠️ ModSecurity V2 - Apache Only)** |
```suggestion
| MODSEC_DISABLE_BACKEND_COMPRESSION | A string value that enables or disables backend compression (Allowed values: `On`, `Off`) (Default: `On`) **(⚠️ ModSecurity V2 - Apache Only)** |
```

2022-10-24 18:18 UTC, theseion approved these changes

2022-11-20 11:01 UTC, fzipi approved these changes

2022-11-20 11:13 UTC, merged